### ISSUE TITLE
1주차 주제 : 선형 리스트

### ISSUE THREAD

**Issue by ticod** [ticod/algorithm-study#1]
## 주제
선형 리스트 (Linear List) 개념 정리 및 직접 구현
<br>
## 기간
2021-04-05 ~ 2021-04-09 밤 12시까지

**Comment by falseman-git** [comment]
확인

**Comment by falseman-git** [comment]
확인2

**Comment by falseman-git** [comment]
https://velog.io/@falseman_go/%EB%A6%AC%EC%8A%A4%ED%8A%B8%EB%8A%94-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B3%A0

**Comment by ticod** [comment]
완료!
https://ticod.tk/linear-list-1/
