### ISSUE TITLE
2주차 과제 : 연결 리스트

### ISSUE THREAD

**Issue by ticod** [ticod/algorithm-study#4]
## 주제
-> 연결 리스트 (Linked List) 개념 정리 및 구현
<br>
## 기간
2021-04-10 ~ 2021-04-16 밤 12시까지

**Comment by ticod** [comment]
https://ticod.tk/linked-list-1/

**Comment by falseman-git** [comment]
https://velog.io/@falseman_go/%EC%84%A0%ED%98%95%EC%9D%84-%EB%B3%B4%EC%99%84%ED%95%9C-%EC%97%B0%EA%B2%B0-%EB%A6%AC%EC%8A%A4%ED%8A%B8
